image: node:8.6.0-alpine

before_script:
#  - 

stages:
  - build
#  - test
#  - deploy

# build-image-mobile-staging:
#  only:
#    - CI # Mudar para a branch development
#  image: docker:latest
#  services:
#    - docker:dind
#  stage: build
#  before_script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#  script: 
#    - cd mobile/
#    - docker build -t registry.gitlab.com/audere/team5c/homepricing/staging/mobile:$CI_COMMIT_SHA .
#    - docker push registry.gitlab.com/audere/team5c/homepricing/staging/mobile:$CI_COMMIT_SHA
#    - docker build -t registry.gitlab.com/audere/team5c/homepricing/staging/mobile:latest .
#    - docker push registry.gitlab.com/audere/team5c/homepricing/staging/mobile:latest

# build-mobile-staging:
#   only:
#     - CI # Mudar para a branch development
#   stage: build
#   before_script:
#     - npm install --progress=false
#   script: 
#     - cd mobile/
#     - npm install yarn
#     - yarn

build-mobile:
  only:
    - CI # Tirar
    - master
    - development
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script: 
    - cd mobile/
    - sh run-docker.sh

build-server:
  only:
    - CI #tirar
    - master
    - development
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
  script:
    - cd server/
    - docker-compose up $
    - docker-compose stop

  