image: node:8.6.0-alpine

before_script:
#  - 

stages:
  - build
#  - test
#  - deploy

build-mobile:
  stage: build
  before_script:
    - npm install --progress=false
  script: 
    - cd mobile/
    - npm install yarn
    - yarn
    - sudo sh run-docker.sh
