version: "2.1"

services:
	api:	
		container_name: api
		build: ./server/api
		enviroment: MONGO_URI=mongodb://mongodb:27017/
		ports:
		  - "3000:3000"
		depends_on: mongodb
	
	mongodb:
		container_name: mongo
		image: mongo
		ports:
		  - "27017:27017"
		restart: on-failure
	
	crawler: 
		container_name: crawler
		build: ./server/crawler
		enviroment: MONGO_URI=mongodb://mongodb:27017/
		depends_on: mongodb

	
	mobile:
		container_name: react-native
		build: ./mobile
