version: "2"
services:

   mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - "27017:27017"
  
   crawler:
    container_name: crawler
    build: ./crawler
    depends_on: 
    - mongodb

   api:
    command: yarn dev
    container_name: api
    build: ./api
    environment: 
    - MONGO_URI=mongodb://mongodb:27017/
    ports:
    - "80:3000"
    depends_on: 
    - mongodb
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules/
    

